# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lYohX7GzC7-OIy9IVTeiuy6jyoMOHqRk
"""

def perHesapla(deger): #perHesapla isimli içine değer alan fonksiyon tanımlıyoruz
    if not deger: #fonk.içindeki değer boş ise değeri boş döndür
        return [deger]  
    else: # boş değilse
        liste = [] # boş bir liste tanımlıyoruz
        for k in range(len(deger)): # fonksiyonun içine aldığı string karakterin uzunluğu kadar döngü oluşturuyoruz
            part = deger[:k] + deger[k+1:] # fonksiyonun içine aldığı string değer en soldaki karakterinden başlanarak sağa doğru sırasıyla bir karakter alınmayarak part değişkenine atanır   
            for m in perHesapla(part): #part değişkenine atanan değer tekrardan perHesapla fonksiyonuna gönderiliyor
                liste.append(deger[k:k+1] + m) # oluşan yeni string listeye değer listeye, var olan değerine yanına ekleniyor.
        return liste #döngülerin sonunda oluşan son liste değeri döndürülüyor.
perHesapla('abcd') # fonksiyona 'abcd' stringini gönderiyor ve farklı string değerlerinin yer aldığı listeyi döndürüyoruz.